import { useState } from 'react'
import { StyleSheet, View, TouchableOpacity, Alert } from 'react-native'
import { FontAwesome5 } from '@expo/vector-icons'
import { useTheme } from '@/hooks/useTheme'
import { ThemedText, ThemedCard } from '@/components/Themed'
import { Campaign } from '@/types/campaign'

interface CampaignCardProps {
    campaign: Campaign
    onPress: (campaignId: string) => void
    onDelete?: (campaignId: string) => void
    onReset?: (campaignId: string) => void
    onEscalate?: (campaignId: string) => void
}

export default function CampaignCard({ campaign, onPress, onDelete, onReset, onEscalate }: CampaignCardProps) {
    const { isDark, theme } = useTheme()
    const [showMenu, setShowMenu] = useState(false)
    const isCompleted = campaign.completedNodes === campaign.totalNodes
    const isAutoGenerated = campaign.id.startsWith('auto_campaign_') || campaign.id.startsWith('theme_campaign_')

    const handleMenuAction = (action: () => void) => {
        setShowMenu(false)
        action()
    }

    return (
        <View style={styles.campaignCardWrapper}>
            <TouchableOpacity
                onPress={() => onPress(campaign.id)}
                activeOpacity={0.9}
                style={styles.cardTouchable}
            >
                <ThemedCard variant="glass" style={styles.campaignCard}>
                    <View style={styles.campaignIcon}>
                        <View style={[
                            styles.iconBox,
                            {
                                backgroundColor: isAutoGenerated
                                    ? `${theme.warning}12`
                                    : isDark
                                        ? 'rgba(255,255,255,0.05)'
                                        : 'rgba(0,0,0,0.05)'
                            }
                        ]}>
                            <FontAwesome5
                                name={isAutoGenerated ? 'robot' : 'globe-americas'}
                                size={22}
                                color={isAutoGenerated ? theme.warning : theme.accent}
                            />
                        </View>
                    </View>
                    <View style={styles.campaignInfo}>
                        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                            <ThemedText variant="heading" style={{ fontSize: 16, flex: 1 }} numberOfLines={1}>
                                {campaign.title}
                            </ThemedText>
                            {isCompleted && (
                                <FontAwesome5 name="medal" size={12} color={theme.warning} />
                            )}
                        </View>
                        <ThemedText variant="body" numberOfLines={2} style={{ fontSize: 12, opacity: 0.55, lineHeight: 17 }}>
                            {campaign.description}
                        </ThemedText>

                        <View style={styles.campaignStats}>
                            <View style={[styles.statBadge, { backgroundColor: isCompleted ? `${theme.warning}15` : `${theme.success}15` }]}>
                                <FontAwesome5 name={isCompleted ? 'medal' : 'check-circle'} size={10} color={isCompleted ? theme.warning : theme.success} style={{ marginRight: 6 }} />
                                <ThemedText variant="code" style={{ color: isCompleted ? theme.warning : theme.success, fontSize: 10 }}>
                                    {campaign.completedNodes}/{campaign.totalNodes} SECURED
                                </ThemedText>
                            </View>
                            {isAutoGenerated && (
                                <View style={[styles.statBadge, { backgroundColor: `${theme.warning}10` }]}>
                                    <FontAwesome5 name="robot" size={9} color={theme.warning} style={{ marginRight: 4 }} />
                                    <ThemedText variant="code" style={{ color: theme.warning, fontSize: 9 }}>
                                        AUTO
                                    </ThemedText>
                                </View>
                            )}
                        </View>
                    </View>
                    <TouchableOpacity
                        onPress={() => setShowMenu(!showMenu)}
                        hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
                        style={styles.menuButton}
                    >
                        <FontAwesome5 name="ellipsis-v" size={14} color={theme.textSecondary} style={{ opacity: 0.6 }} />
                    </TouchableOpacity>
                </ThemedCard>
            </TouchableOpacity>

            {showMenu && (
                <View style={[styles.menuDropdown, { backgroundColor: isDark ? '#1a1a1a' : '#fff', borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)' }]}>
                    {isCompleted && onEscalate && (
                        <TouchableOpacity
                            style={styles.menuItem}
                            onPress={() => handleMenuAction(() => onEscalate(campaign.id))}
                        >
                            <FontAwesome5 name="arrow-up" size={12} color={theme.accent} />
                            <ThemedText variant="caption" style={{ marginLeft: 10, color: theme.accent, fontWeight: '700' }}>
                                ESCALATE
                            </ThemedText>
                        </TouchableOpacity>
                    )}
                    {onReset && (
                        <TouchableOpacity
                            style={styles.menuItem}
                            onPress={() => handleMenuAction(() => {
                                Alert.alert(
                                    'Reset Progress',
                                    `This will reset all progress on "${campaign.title}". Continue?`,
                                    [
                                        { text: 'Cancel', style: 'cancel' },
                                        { text: 'Reset', style: 'destructive', onPress: () => onReset(campaign.id) },
                                    ]
                                )
                            })}
                        >
                            <FontAwesome5 name="redo" size={12} color={theme.textSecondary} />
                            <ThemedText variant="caption" style={{ marginLeft: 10 }}>Reset Progress</ThemedText>
                        </TouchableOpacity>
                    )}
                    {onDelete && (
                        <TouchableOpacity
                            style={styles.menuItem}
                            onPress={() => handleMenuAction(() => {
                                Alert.alert(
                                    'Delete Campaign',
                                    `Permanently delete "${campaign.title}"?`,
                                    [
                                        { text: 'Cancel', style: 'cancel' },
                                        { text: 'Delete', style: 'destructive', onPress: () => onDelete(campaign.id) },
                                    ]
                                )
                            })}
                        >
                            <FontAwesome5 name="trash" size={12} color={theme.error || '#ef4444'} />
                            <ThemedText variant="caption" style={{ marginLeft: 10, color: theme.error || '#ef4444' }}>Delete Campaign</ThemedText>
                        </TouchableOpacity>
                    )}
                </View>
            )}
        </View>
    )
}

const styles = StyleSheet.create({
    campaignCardWrapper: {
        marginBottom: 16,
        position: 'relative',
    },
    cardTouchable: {
        borderRadius: 20,
    },
    campaignCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        borderRadius: 20,
    },
    campaignIcon: {
        marginRight: 14,
    },
    iconBox: {
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    campaignInfo: {
        flex: 1,
        marginRight: 4,
    },
    campaignStats: {
        marginTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    statBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 4,
    },
    menuButton: {
        padding: 8,
        marginRight: -4,
    },
    menuDropdown: {
        position: 'absolute',
        right: 8,
        top: 44,
        borderRadius: 10,
        borderWidth: 1,
        paddingVertical: 4,
        zIndex: 100,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        minWidth: 160,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
})